src/store.ts

`id` will override by `filename` in `transform.ts`

fix: omit `SFCOptions.script.id`

---

README.md
src/SplitPane.vue
src/index.ts
src/output/Output.vue
src/output/types.ts
src/store.ts
test/main.ts

This allows customizing the starting output view (preview, js, CSS, etc) and the visible pane on small viewports. This is useful when embedding the repl in websites like the documentation.
Right now it allows this URL: `http://localhost:3001/?om=js&so...` to start showing the output instead of the editor and start on the js output. These parameters can be customized by the consumer library.

feat: allow starting on a specific view

---

src/editor/FileSelector.vue

Use Enter key to add file, it will emits `File "Comp.vue" already exists.`.
`doneAddFile` will execute twice (`blur` and `keyup.enter`)

fix: adding file using enter emits error

---

src/Message.vue

I have modified the error message style for the playground site as per Evan's suggestion to drop scrolling altogether.
Here is a reference to the original issue on vue/core repository: [Issue](https://github.com/vuejs/core/issues/5412)
before:
after
and for the larger error messages, it's now shown without scrolling on the desktop and still respects the pre-formatted default behavior of the pre-tag.
and only show the scrolling on mobile site:

fix error message styling for issue#5412 on vue/core repo

---

src/output/srcdoc.html

Fixes #32.
Update the module `es-module-shims` from [`@0.10.1 (17.13 KB)`](https://unpkg.com/es-module-shims@0.10.1/dist/es-module-shims.min.js) to [`@1.5.5 (41.51 KB)`](https://cdn.jsdelivr.net/npm/es-module-shims@1.5.5/dist/es-module-shims.wasm.js).
- es-module-shims@0.10.1:
- es-module-shims@1.5.5:
This change adds another ~25 KB to the response size of the `srcdoc.html`, still browsers should benefit from the latest [es-module-shims](https://github.com/guybedford/es-module-shims)/[es-module-lexer](https://github.com/guybedford/es-module-lexer) releases.
No discernible breakage observed.
See also:
https://github.com/guybedford/es-module-shims/pull/239

deps: update to es-module-shims@1.5.5

---

src/editor/FileSelector.vue

- This adds an  increment counter when creating new files. 
-  So users don't have to come up with a new name for every new file now.
| Before | After |
:-------------------------:|:-------------------------:
| <video src="https://user-images.githubusercontent.com/56376387/170051275-bee48980-27e3-4a8c-92e5-6297a35edd6b.mov"></video>  | <video src="https://user-images.githubusercontent.com/56376387/170051501-c94f03b3-d41a-429e-abd6-1d421a3ab5ae.mov"></video> |

enhancement(FileSelector):  add an increment counter for new file names

---

package.json
pnpm-lock.yaml
src/env.d.ts
src/utils.ts

The repl produces very long URLs, we can shorten them by gzipping the stringified state before converting to base64
backwards compatible, `atou` checks if the string was gzipped
<details>
<summary>Example</summary>
Before (2156 bytes):
eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cblx0aW1wb3J0IEdyb3VwIGZyb20gJy4vR3JvdXAuanMnXG4gIGltcG9ydCBJdGVtIGZyb20gJy4vSXRlbS52dWUnXG4gIGltcG9ydCBXcmFwcGVkSXRlbSBmcm9tICcuL1dyYXBwZWRJdGVtLnZ1ZSdcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxHcm91cD5cbiAgICA8SXRlbT5PbmU8L0l0ZW0+XG4gICAgPEl0ZW0+VHdvPC9JdGVtPlxuICAgIDxJdGVtPlRocmVlPC9JdGVtPlxuICA8L0dyb3VwPlxuXG4gIDxHcm91cD5cbiAgICA8V3JhcHBlZEl0ZW0+T25lPC9XcmFwcGVkSXRlbT5cbiAgICA8V3JhcHBlZEl0ZW0+VHdvPC9XcmFwcGVkSXRlbT5cbiAgICA8V3JhcHBlZEl0ZW0+VGhyZWU8L1dyYXBwZWRJdGVtPlxuICA8L0dyb3VwPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24i …

feat: gzip serialized state

---

src/index.ts

Make it possible to create a "preview only" mode without having to render the whole repl and then try to hide the unwanted parts with `display: none`

feat: export Preview component

---

src/codemirror/CodeMirror.vue
src/editor/Editor.vue

In addition, it will be easier to add other modes in the future

fix: add ts and json mode

---

src/codemirror/CodeMirror.vue
src/editor/Editor.vue
src/editor/FileSelector.vue
src/transform.ts

This PR adds support for `.json` files. It includes adding them via the UI, syntax highlighting, and importing them within other files.
This line was a compromise:
```ts
mode?: string | { name: string, json: boolean }
```
It didn't work when I tried to use the correct type from CodeMirror, because of the union. I imagine it'll be possible to do this properly once the TS improvements in 3.3 are available.

feat: local JSON files

---

src/Repl.vue
src/output/Preview.vue
src/output/srcdoc.html
test/main.ts

* Support customize sandbox head tags, such as `<link ref="stylesheet" href="custom/css/file">`
* Support customize sandbox app import code, such as `import SomePlugin/GlobalComponent from 'customLib'`
* Support customize sandbox app usage code, such as `app.use(SomePlugin)`, `app.component('CompName', GlobalComponent)`
Example for global use [ElementPlus](https://github.com/element-plus/element-plus)
```vue
<script setup>
import { Repl, ReplStore } from '@vue/repl'
const store = new ReplStore()
store.setImportMap({
imports: {
'element-plus': 'https://unpkg.com/element-plus@2.2.5/es/index.mjs'
}
})
const customImportStatements = [`import ElementPlus from 'element-plus'`]
const customAppUsageCodes = [`app.use(ElementPlus)`]
const customHeadTags = [
`<link ref="stylesheet" …
```

feat: support for sandbox context customization

---

src/output/moduleCompiler.ts

fix https://github.com/vuejs/core/issues/7304

fix: process all files when dynamic import

---

src/editor/FileSelector.vue
src/store.ts

I've added support for renaming files. A tab can be double clicked to edit the name.
The first file cannot be renamed via the UI. This check is using `i > 0`, the same as the delete X. Arguably it would be better to check the `mainFile` in the store explicitly, but I tried to stay consistent with the existing logic for the X.
The `renameFile` logic in the store does support renaming the `mainFile`, even though that can't be achieved via the UI. It also protects against a couple of error cases that the UI prevents. I thought they might be useful to anyone trying to use `renameFile` directly, rather than going through the UI.
The files are ordered based on the iteration order of an object. This needed to be taken into account in the renaming logic, to avoid the renamed file jumping to the …

feat: add file renaming

---

src/output/srcdoc.html

Console logging currently fails when the logged value is a component instance proxy:
[SFC Playground Example](https://sfc.vuejs.org/#eNo9UMtuhDAM/BXLF1iJTe4IVqp67h/kklKzsMpLSdhVhfj3OrD0EClje8YzXvEjBPFcCFvs0hDnkCFRXsJNudkGHzOsEGls4KXzMMEGY/QWKmZUygEoN3iXMnz9fnoboIe1VCO5H4r15UAF5yU6qCYyxu+8TbmNySddM5O31JdS2jfVugEW6G+HRhnzhoTx91qLpzYL8ezGr5OHbTbMIJMNRmdiBNC9XbFyr1ArBMn1Tv4PYYNHyKvVQTySd3yGfZ96N5LC9kyhkFMXrHDKOaRWyjQO5XiPJHy8S/6JuLg8WxKU7PU7+leiyMIKz9C4/QELhn2b)
Those proxies cannot be passed to `String()` without throwing the error:
> TypeError: Cannot convert object to primitive value
There were a couple of places that potentially pass those proxies to `String()`. The first (line 134) could be removed and replaced by a `typeof` check. The second I have replaced with a `toString()` helper …

fix: console logging for component instance proxies

---

src/transform.ts

related to https://github.com/vuejs/core/pull/6979
**without <script setup>**
before: [see](https://play.vuejs.org/#__SSR__eNpNjdEKhCAQRX9l8MV62MLXcIP9D1/cNAxMRafYJfr3NYslGGbmcufO2cgrhGZdNOkIT0OcAvbCTXPwEWGDqEfYYYx+BpqPqHDC6U8xlR7lYnETDkBJlFVdVsgZXKK7BMDgrY/d8amiUStan8Z+jNxy8fYPzgL1HKxEnRUANwwGK1N6CmKYIH35xlvDss3b2y1P+LVnqDHsol/s9fGenKqKKvgTWgJk/wG5q1dV)
after:

fix: improve code gen when using cssVars in SSR

---

src/output/Preview.vue

After adding CSS properties to it, I noticed that they didn't take effect. While modifying the `codeToEval`, I tried using `Promise.resolve().then` and `setTimeout(()=>{},0)` to execute it, but it still didn't work. However, when I adjusted the timeout to 1ms, it started working. Did it internally use `setTimeout`? Interestingly, I observed that other synchronous operations were working fine. This situation has left me confused. Nevertheless, the current changes I made are effective.
[demo](https://play.vuejs.org/#eNpNjDEOwjAMRa8SvNOItYRIbNyAJUuaWIAwdZSkFajq3XHDwmb//99b4JxSN08IPZiKr0S+onWjUiY+ZhXIl3JyMPDbQYuluB/sBYlYXTlT3BktQSO0IHIZ/SeSt9QPoSqBE8Y27ES3/GSDD89b5mmM+8DEuc8Yj1u1bp5GWli/1UU3ug==)
Reproducible steps:
1. Open the demo.
2. Delete the style tag.
3. Restore the style tag. …

fix css attribute HMR failure

---

src/output/srcdoc.html

prevent `a` tag from jumping to another tab when `href="javascript: void(0)"`

---

src/monaco/Monaco.vue
src/store.ts

When switching between tabs, the cursor will be lost, and you need to re-click the file content to continue editing.
This PR is able to save its cursor and selection when switching files, no extra mouse clicks required.
before:
https://github.com/vuejs/repl/assets/15389209/34388f92-0632-43a5-a442-1ec8d7a2c9d3
after:
https://github.com/vuejs/repl/assets/15389209/811180bb-298f-49bd-9b28-839dd680ac3f

feat: support to keep selection and cursor position

---

src/monaco/Monaco.vue

Enable fixedOverflowWidgets to render overflowing content widgets as ‘fixed’ (defaults to false). It is very useful when the REPL is embedded.
before:
after:

fix(monaco): enable `fixedOverflowWidgets` option

---

src/editor/EditorContainer.vue
src/store.ts
src/transform.ts

- Show error messages always. `compiler-sfc` errors should be displayed, even if in Monaco editor. 
- `compileFile` will return an error list now, so that we can collect all errors when first init, and they're won't be overwritten (if there's no errors in the next file).
Example: https://play.vuejs.org/#eNo9jr0OgjAUhV/l2qU4KHE1hYTN0c2lC4ELNulf2gtL03f3ionjd07OTxFDjNd9Q3EXKk/JRIKMtEWwo187LShr0WtvXAyJoEDCBSosKTiQHJPaaz8FnwlcXqH7+o18oLUBXiHZ+STP2s+4GI/PFGJWQ9+wotrfGFczELpoR0ImAPW+9aUcdbWqlulQjY8bwX5xYUbLx9g/nqn2nxb1AxpCR1Q=
Fix:
- when first open, there's no errors.
- show errors with-in Monaco editor.

refactor: error messages

---

src/Repl.vue
src/output/Output.vue
src/output/Preview.vue

I have exposed a `reload` function in Repl, which reloads the preview `iframe`. It allows you to reload the preview without refreshing the entire page.

feat: add `reload` function

---

src/editor/EditorContainer.vue

First of all, thank you for adding the show-error function, which is really helpful for debugging code. Secondly, this PR hopes to remember the user's choice of show-error, so as to avoid having to manually refresh every time. Click the switch.

feat: memorize show error state

---

src/monaco/Monaco.vue
src/store.ts

related: https://github.com/vuejs/repl/pull/99

refactor: save editor view state in store

---

src/Message.vue

refactor: improve message color

---

src/Repl.vue
src/output/Preview.vue
src/output/srcdoc.html

In the environment of poor network, loading cdn script and initializing preview will be blank for a long time.
Implement custom loading animation for the initial placeholder content of iframe
```js
() =>
h(Repl, {
...
previewOptions: {
placeholderHTML: ` <style>
html, body {
width: 100%;
height: 100%;
}
body, html {
display: flex;
align-items: center;
justify-content: center;
}
.loading {
font-size: 20px;
}
</style>
<div class="loading">Loading...</div>`
}
})
```

feat: support custom display placeholder content

---

package.json
pnpm-lock.yaml
src/monaco/vue.worker.ts
vite.config.ts
vite.preview.config.ts

After @volarjs pakcages 1.10.10, polyfills for node modules are no longer required.
See https://github.com/volarjs/volar.js/pull/70

refactor: remove `path-browserify` polyfill

---

src/editor/FileSelector.vue

- remove the ugly black on white input not respecting the theme
- position the editing on top of the original title
- autogrow the size of the tab while editing

refactor: improve edit filename ui

---

src/SplitPane.vue

CodeMirror Editor tries to auto-size when it starts. If the Repl start in Output mode on small layouts CodeMirror will not be able to autosize because it has `display: none`. From the POV of user the only solution is to change editor tabs to see the code (if it has more tabs).

fix(codemirror): fix codemirror editor showing nothing on start on small layouts when starting in ouput mode

---

index-dist.html
index.html

Prevents bottom part of the playground hiding under mobile browsers bottom bar

feat(playground): use a height of 100dvh with fallback to original 100vh

---

src/Message.vue

The messages are by default below the toggles and the text can be unreadable. The message can be closed to show the toggles, but the toggles cannot be removed to see the message.

feat(messages): place error messages in editor in front of bottom toggles

---

src/output/Preview.vue

relate https://github.com/vuejs/core/issues/9847
In #88, I addressed the issue of styles being lost during hot updates by implementing asynchronous loading of styles. However, this resulted in an error in obtaining the correct styles within the onMounted hook. Since the style loading mechanism has been updated in #116, resolving the problem of style loss during hot updates, I have removed the setTimeout in this PR.
https://github.com/vuejs/repl/assets/55641773/f62731f0-3ae3-44c4-99c5-60eac65908ce

fix(Preview): fixing incorrect styles during onMounted

---

src/output/srcdoc.html

Fix the problem of opening a new tab when clicking on the a tag does not have href attribute

fix: don't overwrite `a` tag without href 

---

src/Repl.vue
src/SplitPane.vue
src/editor/EditorContainer.vue
src/editor/FileSelector.vue
src/import-map.ts
src/index.ts
src/monaco/Monaco.vue
src/monaco/env.ts
src/output/Output.vue
src/output/Preview.vue
src/output/moduleCompiler.ts
src/store.ts
src/transform.ts
src/types.ts
test/main.ts

- Separate import map and store as two functions
- `useStore`: keep most of the functionality, and refactor to composables
- `useVueImportMap`: extract links of the Vue import map.

refactor!: useStore & useVueImportMap composable

---

src/output/moduleCompiler.ts

Dynamic imports were not functioning correctly because the rewritten import paths lacked the necessary "src/" prefix.
I have updated the path rewriting logic to correctly prepend "src/" to the import paths. This ensures that dynamic imports resolve correctly and function as expected.
fix: https://github.com/vuejs/repl/issues/208
[Preview](https://repl-git-fork-youxam-dynamic-import-vuejs.vercel.app/#eNqVU8tOwzAQ/JXFl7ZSkxy4RWklXgeQeAg4+pImm2Jwbct2Squq/87aIaEIqMTN+/B4Zna9Y2fGpOsWWc4KV1lhPDj0rZlzJVZGWw87sNhMocZGKDxzW1VdaKooVB720Fi9ghEBjLjiqtLKefDlAmaw4wqg6lvzXwHG4wnM5tC9NB6lWagEOqPJhKv9F2TIE+b/MXqAWjgjyy3WhEJ6xk0pHVK9yDrVpJcCjyvq8kgRQPFis5imoywXKGOWAqFM62GdrHSNcsbZgM0Z+K1BSlUvWL0t9Iazz0uXQ0+Ay3q8GNViTWii+Q7VvxalByIxOkmSYjAVcuHoEvmdDjnikM2TpFOQEXT/SqemyA40sinzjvxpxDJ9dVrREsSpEX+CExLtvfGC/OMs7 …

fix: dynamic import

---

src/SplitPane.vue

When dragging the view area to view the responsive effect, since the width calculation percentage is now an integer, some edge case values will be skipped directly, making it difficult to meet the conditions you want to test.

fix: refine dragging view area

---

src/Repl.vue
src/monaco/Monaco.vue

feat: add `autoSave` option

---

src/codemirror/CodeMirror.vue

@sxzz I didn't notice before that `editor` may have two situations, causing `CodeMirror` to be ignored. 😅

feat: `CodeMirror` support `autoSave` option

---

src/Repl.vue
src/SplitPane.vue
src/output/Output.vue
src/output/Preview.vue

When dragging a view, the size of the view area is displayed in real time, without the need to confirm through developer tools.

feat: show view size while dragging split pane

---

src/Repl.vue
src/editor/MessageToggle.vue
src/output/Preview.vue

- Preview 面板运行时错误可配置关闭
- Editor ShowError 文档支持定制

feat: add more customization options

---

src/editor/FileSelector.vue

When the file name is empty, it looks weird after the input box loses focus.

fix: cancel creating new file

---

src/Repl.vue
src/codemirror/CodeMirror.vue
src/editor/EditorContainer.vue
src/editor/ToggleButton.vue
src/types.ts
test/main.ts

feat: add `autoSave` toggle button

---

src/SplitPane.vue

[mobile] The store.`showOutput` configuration may not work when `layoutReverse: true` is configured.

fix(split-pane): rendering order comes from the store.show-output

---

src/store.ts

```ts
const store = useStore();
store.setImportMap({}, true)
```
```ts
getImportMap(): ImportMap
setImportMap(map: ImportMap, merge?: boolean): void
```

feat(store): return `setImportMap` and add `merge` parameter

---

README.md
src/index.ts
src/output/Preview.vue
src/output/Sandbox.vue

You can control the preview yourself without loading the editor.
1. Separate `Sandbox` from `Preview`
2. Export `Sandbox` component
```js
import { Sandbox, useStore } from '@vue/repl'
const store = useStore(
{
vueVersion: ref('3.5.13'),
},
location.hash,
)
return () => h(Sandbox, { store })
```

feat: export `Sandbox`

---

src/store.ts

Need to check ImportMap after deserialize because `builtinImportMap` data will be deleted during `store.serialize`.
```ts
/**
* Deserializes the given string to restore the REPL store state.
* @param serializedState - The serialized state string.
* @param checkBuiltinImportMap - Whether to check the built-in import map. Default to true
*/
deserialize(serializedState: string, checkBuiltinImportMap?: boolean): void
```

fix(store): to check ImportMap after deserialize

---

package.json
src/core.ts
src/index.ts
vite.config.ts

add new entries to import `compileFile`
resolve #304
edit: realised that we couldve import more utilities besides `compileFile`, thats why i created a new export entry `core.ts`. The name might be not appropriated though

feat: add core entry for node usage

---

src/Repl.vue
src/output/Output.vue
src/output/Sandbox.vue
src/output/SsrOutput.vue
src/output/srcdoc.html
src/store.ts
src/types.ts
test/main.ts

This adds an option to show the SSR output.
My goal was to make it a bit easier to investigate SSR hydration problems by showing the generated HTML directly in the UI.
The new option is disabled by default, but it is enabled in `test/main.ts`.
I've also exposed the SSR context object, which is populated if teleports or sync watchers are used.

feat: show SSR output

---

src/import-map.ts
src/output/Sandbox.vue

close #356
- Use `https://cdn.jsdelivr.net/npm/vue@3.6.x/dist/vue.runtime-with-vapor.esm-browser.js` as the runtime import.
- Use `createVaporApp` or `createVaporSSRApp` when vapor mode is supported and `App.vue` is a vapor component.

fix: handle Vue 3.6+ vapor runtime imports correctly

---

src/transform.ts

Add `isCustomElement` argument for `doCompileScript()` to pass `isCustomElement` to `CompileScript()`.
Closes vuejs/core#13615.

fix: add support for custom elements for `CompileScript`
