README.md

i think `../src` was maybe a bit too literal :)

docs: update import path in example

---

src/Repl.vue
src/editor/Editor.vue
src/editor/FileSelector.vue
src/index.ts
src/output/Output.vue
src/output/Preview.vue
src/output/moduleCompiler.ts
src/store.ts
src/transform.ts

extract `ReplStore` interfaces to type `Store`

refactor: extract store interface

---

src/index.ts

export `compileFile`, so we can extend `Store` without copy `transform.ts` file

feat: export `compileFile`

---

src/editor/FileSelector.vue
src/store.ts

I want to hide library file `element-plus.js` in [element-plus.run](https://element-plus.run/)
https://github.com/element-plus/element-plus-playground/blob/56cb42526707461e5ef537551f3a65de1cae8c09/src/store.ts#L104-L108

feat: add hidden file

---

.gitignore
src/Message.vue

2 things:
1. fix small screen error msg covered toggle button
2. fix media breakpoint not consist between toggle and msg
before:
after:

fix: small screen error msg covered toggle button

---

README.md

Was getting a syntax error when copy/pasted. This fixes it.

Fixing runtime error

---

src/codemirror/CodeMirror.vue
src/codemirror/codemirror.ts

Add `sublime` keymap which can support comments, indent less, and more.
https://codemirror.net/5/demo/sublime.html

feat: add `sublime` keymap

---

src/transform.ts

see [playground]( https://sfc.vuejs.org/#__DEV__eNp9kE1ug0AMha9izSatFGaqdBeRND1HpwsCDqFlfuQxdIG4ew1kQVMpu/F79vs8HtR7jLrvUO1VzuhiWzAerQfIq6afHwDDAG1xxja96RZ9zVcYx7nFLD25WU1KmUpqIkNC7qJM+vpgFSerxG1cDMQwEF5GuFBwsBH4xvoy+MQ3DBxA/KePz+cpe0k7qq1ahjNXRP2VgpeVh2kNezOEsIdZmTSJnWqrrswx7Y3pfPyudRmcOYlnqPPcOMyq4E6veqd3L/KbxGtdY3LZmcJPQhKiVdtVuBGxR8oIfYWE9BB21/sHeOf9g05MOfeoxl/kcpRb)
need to add a semicolon.

fix: improve code with optional chain

---

src/codemirror/codemirror.css
src/codemirror/codemirror.ts

shortcuts: https://codemirror.net/5/demo/search.html
closes #65

feat: add search and replace

---

src/editor/MonacoEditor.vue
src/monaco/Monaco.vue

Synchronize the font size of CodeMirror and Monaco editor

fix: larger font size

---

src/monaco/Monaco.vue

https://github.com/vuejs/repl/assets/15389209/071be225-5813-48a6-ab95-86ee2786af71

feat: support custom file go to difinition

---

src/editor/CodeMirrorEditor.vue

refactor: use defineOptions

---

src/output/Preview.vue
src/output/moduleCompiler.ts
src/output/srcdoc.html

fix: multiple style tags

---

src/editor/MessageToggle.vue

The wrapper will cover the scrollbar.

fix: change message toggle position

---

src/monaco/env.ts
src/monaco/vue.worker.ts
src/store.ts

close #124
Supports dynamically downloading typescript library from CDN, so it is no longer necessary to bundle it, and we can support users to choose their own version.

feat: download TS dynamically

---

src/editor/FileSelector.vue
src/store.ts

fix: filename index auto-increment

---

package.json
pnpm-lock.yaml
vite.preview.config.ts

fix: use dev version of compiler

---

src/monaco/Monaco.vue

relate: [vuejs/core](https://github.com/vuejs/core/issues/9538)

refactor: add tabSize configuration

---

src/output/srcdoc.html

fix: default to white color on dark theme

---

package.json
pnpm-lock.yaml
src/editor/FileSelector.vue
src/jsx.ts
src/output/Preview.vue
src/transform.ts

closes #57, closes #68, closes #241

feat: jsx for vue
